Use exec.d to set PYTHONPYCACHEPREFIX
paketo-buildpacks/cpython pull request #352
Opened 2022-06-16 18:31 UTC by ryanmoran

## Summary

We will need to use an `exec.d` binary to set the `PYTHONPYCACHEPREFIX` with the dynamic value for `$HOME`. This is because the values placed into the normal environment variable file API are not interpolated/expanded before the process is executed.

The original implementation of this feature (https://github.com/paketo-buildpacks/cpython/pull/340) assumed this interpolation/expansion incorrectly and the bug was being resolved with a surprising and unexpected behavior. Specifically, the `__pycache__` contents we being written to `/workspace/'$HOME'/.pycache`.

This resolved the immediate bug in that these files were no longer being written into what should have been a read-only layer, but then caused another bug in that it would easily crash a `watchexec` process that was restarting a process when there were modifications to the `/workspace` directory.

## Use Cases

Enables https://github.com/paketo-buildpacks/python/pull/478 to be merged.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-06-16 19:46 UTC, robdimsdale requested changes

2022-06-16 19:46 UTC, robdimsdale commented on cmd/env/internal/run_test.go
> +		it("sets it to $HOME/.pycache", func() {
I think this should be something like: "it preserves the existing value"

2022-06-16 21:03 UTC, ryanmoran commented on cmd/env/main.go
> +	err := internal.Run(os.Environ(), os.NewFile(3, "/dev/fd/3"))
I think the spec doesn't do a very good job of connecting the dots for how the feature works. The [original RFC](https://github.com/buildpacks/rfcs/blob/main/text/0057-exec.d-shell-free-profile-d.md) explains it a bit better.

2022-06-17 02:17 UTC, robdimsdale commented on cmd/env/main.go
> +	err := internal.Run(os.Environ(), os.NewFile(3, "/dev/fd/3"))
That's helpful, but I think I'm still missing the magic behind fd 3.

My readings on fd 3 suggests it's typically the first file descriptor made available to a process when it asks the operating system for a file (as fd 0,1, and 2 map to stdin, stdout, and stderr, respectively).

I guess my concrete question - that isn't answered by the RFC - is this: is there anything special about fd 3 with respect to exec.d, or is it a simple interface for a process to write data to a known location such that the lifecycle can pick up the values? E.g. typically most commands would output any data to stdout (i.e. fd 1) - the lifecycle instead looks for fd 3.

2022-06-17 02:18 UTC, robdimsdale commented on cmd/env/main.go
> +	err := internal.Run(os.Environ(), os.NewFile(3, "/dev/fd/3"))
Also, to be clear, this isn't a blocking concern. I'm happy that this works and conforms to the spec (and RFC). I'm just trying to build up my context around historical architecture decisions.

2022-06-17 13:43 UTC, joshuatcasey commented on cmd/env/main.go
> +	err := internal.Run(os.Environ(), os.NewFile(3, "/dev/fd/3"))
I suspect `fd 3` was just a convenient tool to use since `STDOUT` can attract so much additional noise. as you said. I think it's unfortunate because it feels more like an Easter Egg in the lifecycle than a built-in feature but I get the rationale.

2022-06-17 13:45 UTC, joshuatcasey commented on cmd/env/internal/run.go
> +func Run(env []string, output io.Writer) error {
Is the reason for injecting the env as a `[]string` from `os.Environ()` for testing purposes? Or was there another reason why `os.GetEnv` was avoided?

2022-06-17 14:28 UTC, ryanmoran commented on cmd/env/main.go
> +	err := internal.Run(os.Environ(), os.NewFile(3, "/dev/fd/3"))
I imagine that is context that was not ultimately recorded in the RFC. It may be in the comments around the PR merging the RFC or it could be in the YouTube recordings of the Working Group meeting from that time period. I don't have the background. I'm just following what the spec says now.

2022-06-17 14:30 UTC, ryanmoran commented on cmd/env/internal/run.go
> +func Run(env []string, output io.Writer) error {
Yes, for testing. Environment variables are effectively global variables and should be treated as such. Isolating globals by passing them through an interface like a function signature is preferred to accessing the global directly from within the code under test.

2022-06-17 14:33 UTC, ryanmoran commented on cmd/env/internal/run_test.go
> +		it("sets it to $HOME/.pycache", func() {
👍

2022-06-17 17:21 UTC, merged