Add support all stacks
paketo-buildpacks/cpython pull request #398
Opened 2022-08-18 05:07 UTC by jpena-r7

## Summary

This change adds support for all stacks by adding logic to build python from source based on the builder stack.

* For bionic and jammy stacks there is no change and dependencies will be installed from the dep server.
* For custom stacks (not explicitly defined in buildpack.toml) python will be built and installed from source.
* Unit tests and integration tests have been updated to support the changes and all tests pass.
    * Tests took about 20 minutes to run on an intel macbook pro.
* A public amazonlinux stack and builder were used for testing. The images will remain available and public for future testing.
* Note that offline tests are skipped for custom stacks.

**NOTE about the `org.cloudfoundry.stacks.cflinuxfs3` stack**

I found that this stack is based on bionic so I added it to the list of dependencies satisfied for `io.buildpacks.stacks.bionic`. I have not tested this stack, but I believe it should work.

## Use Cases

This allows the cpython buildpack to be used on non-paketo stacks and builders. While most users will be able to use paketo builders and stacks, there are situations where ubuntu-based stacks will not work for some users. In those cases, they have the ability to create their own stacks and builders.

It is expected that any users that want to build python from source on their own stack and builder will have the necessary packages installed in the build image. [This](https://github.com/jericop/amazonlinux-stack) stack repo and [this](https://github.com/jericop/amazonlinux-builder-buildpackless-base) builder repo are examples and were used to validate this change.

Users can customize how python is configured and installed by setting the `BP_CPYTHON_CONFIGURE_FLAGS` environment variable at build time. Supported flags are documented [here](https://docs.python.org/3/using/configure.html). It is expected that anyone setting this will ensure that the necessary libraries, headers, etc, are available in the build image. This allows users to have fine grained control over how python is configured and installed.

## Checklist

* [ ] I have viewed, signed, and submitted the Contributor License Agreement.
  * I have reviewed it, but have not signed or submitted anything. 
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

2022-08-23 15:38 UTC, robdimsdale requested changes
This is great! I love that I can check out the PR and run all the unit/integration tests and see it working as intended against your custom stack. That's really helpful.

I have a couple of minor comments, and a couple of larger architectural questions.

But, perhaps the biggest blocker to merging is that our current dependency automation will overwrite the `buildpack.toml` file and remove your additions. As I've mentioned before, we are actively working on rewriting this dependency automation, and we can make it so that we do not clobber the whole dependencies section of the buildpack.toml file. If we were to merge this PR before that change is complete, we will have to temporarily disable the dependency automation, and manually bump new dependencies when they become available.

That is a question for @paketo-buildpacks/python-maintainers - do we feel the burden of manually watching dependencies while we work on the dependencies infrastructure is small enough to feel comfortable disabling it and merging this PR?

Regardless of whether we can merge it now, if you can address my inline comments, we can keep this PR in a state where it's ready to merge at any time.

To be clear: I definitely expect to merge this PR at some point. It's a question of "when", not "if".

2022-08-23 15:38 UTC, robdimsdale commented on integration/default_test.go
> +				MatchRegexp(`      Completed in \w+\.\d+`),
I assume this change from `\d` to `\w` is because the compilation process can take sufficiently long that the output includes minutes as well as seconds?

I am on the fence about whether to make the regex tighter and test for up to `12h34m56.789s`. On the one-hand, it is a better test, and avoids potential false positives where we got unexpected values that happen to satisfy `\w`. On the other hand, the regex becomes much harder to read and I'm not sure the benefit is worth the cost.

Do you have thoughts here?

2022-08-23 15:38 UTC, robdimsdale commented on integration/init_test.go
> +type Builder struct {
This works - the integration tests pass - but I think I'd like to see us adopt the pattern found in the [dotnet-publish buildpack integration tests](https://github.com/paketo-buildpacks/dotnet-publish/blob/fc204dd623cea17ba90f6b6abf32845f698402f0/integration/init_test.go#L155-L166)?

Specifically, something like:

```
var (
	builder                           struct {
		Local struct {
			Stack struct {
				ID string `json:"id"`
			} `json:"stack"`
		} `json:"local_info"`
	}
)
...
func TestIntegration(t *testing.T) {
	cmd := pexec.NewExecutable("pack")
	Expect(cmd.Execute(pexec.Execution{
		Args:   []string{"builder", "inspect", "--output", "json"},
		Stdout: buf,
		Stderr: buf,
	})).To(Succeed(), buf.String())

	Expect(json.Unmarshal(buf.Bytes(), &builder)).To(Succeed(), buf.String())

	suite := spec.New("Integration", spec.Report(report.Terminal{}), spec.Parallel())
	if strings.Contains(builder.Local.Stack.ID, "jammy") || strings.Contains(builder.Local.Stack.ID, "bionic") {
            suite("Offline", testOffline)
        }
        suite("Default", testDefault)
        suite("LayerReuse", testLayerReuse)
	suite.Run(t)
}
```

I think consistency across buildpacks will help buildpack maintainers, and I think the above suggestion is at least as clear as what currently exists.

2022-08-23 15:38 UTC, robdimsdale commented on integration/offline_test.go
> +		if builder.IsPaketoBuilder {
If we adopt the suggestion above I think we will be able to drop this `if` condition.

2022-08-23 20:24 UTC, robdimsdale commented on integration/init_test.go
> +type Builder struct {
After writing the comment above, i saw that the dotnet buildpacks have both patterns - the one you originally suggested and the one i suggested.

I still have a slight preference for my suggestion, as we should skip the entire suite of tests rather than skipping each one with an `if` statement. I think it's logically more clear as to what the intention is.

But, I'm open to other thoughts here.

2022-08-26 18:07 UTC, jpena-r7 commented
I need to create a new fork and PR in my own account (not rapid7 org) in order for the CLA to function properly. I will implement the above mentioned comments and suggestions in a new fork and PR and will link to this one for reference.

2022-08-28 20:08 UTC, jpena-r7 commented on integration/default_test.go
> +				MatchRegexp(`      Completed in \w+\.\d+`),
That is correct. I agree that having a tighter regex would be preferable, but I don't see any risk for false positives because the only output that is produced (without debugging) is the `Completed in ` message after installation.

One compromise is to require that the first character is a digit and then use the alphanumeric match, where `\w+` would become `\d+\w*`. Either way works. Just let me know what you prefer and I can update it accordingly.

2022-08-28 20:48 UTC, jpena-r7 commented on build.go
> +			duration = downloadDuration + installDuration
I thought about doing this initially, but I decided against it because the tests would need to have conditional logic to determine the stack and then expect outputs based on the type of install. I plan to leave it as unless you feel that it should be updated. Just let me know.

2022-08-28 21:07 UTC, jpena-r7 commented on detect_test.go
> +			Expect(os.Setenv("BP_CPYTHON_VERSION", "some-version")).To(Succeed())
Sounds good. Implemented in this commit: 
https://github.com/jpena-r7/cpython/commit/bbe126f05713f87f1cb15005f50bb494389e94b4

2022-08-29 01:37 UTC, jpena-r7 commented on integration/init_test.go
> +type Builder struct {
I agree with you about following the dotnet pattern and it clarifies the intention as you have noted. Thanks for the helpful example code. I have implemented it in this commit:
https://github.com/jpena-r7/cpython/commit/f3ebc7c05fc3d8a25c5c8afb81e7b9b083997b91

2022-08-29 01:39 UTC, jpena-r7 commented on buildpack.toml
> +    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
Thanks for the background information on it. I only added it back after noticing that I had removed it during my testing and development. It has been removed in this commit:
https://github.com/jpena-r7/cpython/commit/df9348f694123017cdae715a1fd45792e87da187

2022-08-29 01:41 UTC, jpena-r7 commented on integration/offline_test.go
> +		if builder.IsPaketoBuilder {
Agreed and done in this commit:
https://github.com/jpena-r7/cpython/commit/f3ebc7c05fc3d8a25c5c8afb81e7b9b083997b91

2022-08-29 02:10 UTC, jpena-r7 commented on detect.go
> +	ConfigureFlagsSource string `toml:"configure-flags-source"`
Sounds good. Removed in this commit:
https://github.com/jpena-r7/cpython/commit/0a011188992dbebaef412f1dce3a172210f385e1

2022-08-29 02:17 UTC, jpena-r7 commented on build.go
> +			// When installing from source set this to 1 to ensure source code is extracted correctly
Update in this commit:
https://github.com/jpena-r7/cpython/commit/373e6eeea4c0bc4aed8e199d1f7a6fee1c565ccb

2022-08-29 02:37 UTC, jpena-r7 commented on README.md
> +### `BP_CPYTHON_CONFIGURE_FLAGS`
Agreed that it is a bit ambiguous, so I updated it with a bit more context in the commit below. Hopefully that is good.
https://github.com/jpena-r7/cpython/commit/2c70256858ba8cbb57487f785e13a44d19afa28a

2022-08-30 17:16 UTC, jpena-r7 commented on integration/default_test.go
> +						"BP_CPYTHON_VERSION": defaultDependency.Version,
This can be changed to a different version if needed as done in `layer_reuse_test.go`, but the test does validate that a specific version will be installed so I left it as is.

2022-08-30 18:08 UTC, robdimsdale commented on integration/default_test.go
> +				MatchRegexp(`      Completed in \w+\.\d+`),
I think it's fine as-is.

2022-08-30 18:08 UTC, robdimsdale commented on build.go
> +			duration = downloadDuration + installDuration
Ah, yes, the logging test would have conditional logic. I think this is fine as-is, then.

2022-08-30 18:35 UTC, robdimsdale commented on integration/default_test.go
> +						"BP_CPYTHON_VERSION": defaultDependency.Version,
As discussed in-person, the intention of this test was to verify that the `BP_CPYTHON_VERSION` environment variable selects the non-default version of the cpython dependency.

That being said, as we also discussed in-person, this behavior is implicitly exercised in the `layer_reuse_test.go` test, so we could potentially remove this test. But if we did that, we should make sure that the `layer_reuse_test.go` validates that the different python versions were correctly installed (e.g. by running `python --version`).

For now, I think the simplest thing for this PR is to change this test to use the previous dependency version. Either hard-coded or dynamic is fine by me.

2022-08-30 18:40 UTC, robdimsdale commented on build.go
> +			err = os.Mkdir(sourcePath, 0755)
I think explicitly setting the permissions as `0755` is fine in the general case, but i just want to call out that this can lead to brittle tests, depending on your `umask`.

See this similar issue I encountered in another repo: https://github.com/paketo-buildpacks/jam/issues/99

2022-08-30 18:48 UTC, jpena-r7 commented on integration/default_test.go
> +						"BP_CPYTHON_VERSION": defaultDependency.Version,
I can update it. Do you have a preference for the other version being installed or is the logic below acceptable?

```
			for _, dependency := range buildpackInfo.Metadata.Dependencies {
				if otherVersion != defaultDependency.Version {
					otherVersion = dependency.Version
					break
				}
			}
```

2022-08-30 19:02 UTC, robdimsdale requested changes

2022-08-30 19:02 UTC, robdimsdale commented on integration/init_test.go
> +	Expect(cmd.Execute(pexec.Execution{
Since you created this PR, we now have a better way to do this:

`pack.Builder.Inspect.Execute()`

Sorry to make this a moving target!

2022-08-30 19:07 UTC, robdimsdale commented on integration/default_test.go
> +						"BP_CPYTHON_VERSION": defaultDependency.Version,
That's fine. There's no constraint that we use any particular version (i.e. a previous or later version than the default). Literally any other version is fine, so this works!

2022-08-30 20:59 UTC, jpena-r7 commented on integration/init_test.go
> +	defaultDependency postal.Dependency
My initial approach was going to determine the version from the already parsed `buildpack.toml` file, but the reason I opted for this approach instead is because that logic is already contained in `service.Resolve`. Otherwise I have to convert the `default-versions` value from `3.10.x` to an actual version and then compare the other versions in that minor release to find the latest. It just seemed like less effort to maintain in the long-term since that functionality is already available in `service.Resolve` and presumably tested as well.

We can reduce the number of objects by getting the dependency this way.

```
defaultDependency, err = postal.NewService(cargo.NewTransport()).Resolve("../buildpack.toml", "python", "default", builder.Local.Stack.ID)
```

I can also create a variable to store the version only, but I will need to store the `postal.Dependency` regardless in order to get the version.

```
defaultDependency, err = postal.NewService(cargo.NewTransport()).Resolve("../buildpack.toml", "python", "default", builder.Local.Stack.ID)
Expect(err).NotTo(HaveOccurred())
var defaultVersion string = defaultDependency.Version
```

Let me know if you have a suggestion for a different approach for finding the default version. My goal is to avoid copying the code from `service.Resolve`.

2022-08-30 21:04 UTC, jpena-r7 commented on installer.go
> +	if err := os.Chdir(sourcePath); err != nil {
From my testing I believe it does have to be run from that directory. I tried setting the working directory and running from `/workspace`, but it failed and it only worked from the source directory.

2022-08-30 21:07 UTC, jpena-r7 commented on installer.go
> +	if err = os.Chdir(filepath.Join(layer.Path, "bin")); err != nil {
Yes. My goal was to use a relative symlink, but let me know if you prefer a fully qualified path link instead.

2022-08-31 13:13 UTC, robdimsdale commented on installer.go
> +	if err = os.Chdir(filepath.Join(layer.Path, "bin")); err != nil {
Nope - this is fine. I just wanted to make sure I understood. Thanks!

2022-08-31 13:16 UTC, robdimsdale commented on installer.go
> +	if err := os.Chdir(sourcePath); err != nil {
That's fine. I'm not particularly surprised that the `configure` script had to be run from the `sourcePath` - I just wanted to clarify that was why we were changing the working directory.

I think it would be a useful future refactor - outside of the scope of this PR - for `pexec` to be able to have its working directory set, rather than having to change directories before invoking the executable, and then remembering to change back after the execution completes.

I'm happy with what we have for this PR.

2022-08-31 13:20 UTC, robdimsdale commented on integration/init_test.go
> +	defaultDependency postal.Dependency
Yeah, I think what you have is reasonable given that we would have to reproduce the version-matching logic (including matching on stacks and parsing versions as semver).

I am not concerned about inlining the constructor - my issue isn't with the named variables, but the fact that we have to create objects that we don't need. It adds a layer of complexity and confusion to look at this test and have to determine whether the `cargo.NewTransport()` is actually used or not. Especially in the offline case, I could see this causing confusion.

Again, I think this is fine given what we have to work with. I think there is a future refactor to `packit` to explore if we can extract the version-parsing and matching logic from the transport. Phrased another way, it seems that `postal.NewService()` is doing multiple, distinct concerns, and some of them can be abstracted away to simplify the code. That's outside of the scope of this PR, so we can go with what we have.

2022-08-31 13:22 UTC, robdimsdale commented on integration/init_test.go
> +	defaultDependency postal.Dependency
> I can also create a variable to store the version only, but I will need to store the postal.Dependency regardless in order to get the version.

Yes, I think it's preferable to store only the version (as a string) for the default dependency. I don't think there is any benefit to storing the entire dependency, and it adds the possibility for confusion later on when the dependency is referenced.

2022-08-31 14:33 UTC, robdimsdale commented on installer.go
> +	if err := os.Chdir(sourcePath); err != nil {
I took another look at packit, and `pexec.Execution` has a `Dir` field. Have you tried setting that? Is that what you mean when you said:

> I tried setting the working directory and running from /workspace, but it failed and it only worked from the source directory.

2022-09-01 12:59 UTC, robdimsdale commented on integration/init_test.go
> +	builder       occam.Builder
I think this `builder` variable is only used in the `TestIntegration()` setup function below - the same place is is defined. So we can inline it with:

```
builder, err := pack.Builder.Inspect.Execute()
Expect(err).NotTo(HaveOccurred())
```

2022-09-01 13:02 UTC, robdimsdale commented on detect_test.go
> +	context("when the BP_CPYTHON_CONFIGURE_FLAGS env var is set", func() {
I think we can put this context inside the context above (setting `BP_CPYTHON_VERSION`) - it will be more obvious that this test case is only meaningful within that broader context, and it will allow us to remove the `t.Setenv("BP_CPYTHON_VERSION")` a second time.

2022-09-04 22:26 UTC, jpena-r7 commented on integration/default_test.go
> +						"BP_CPYTHON_VERSION": defaultDependency.Version,
Sounds good. This has been updated as requested in this commit:
https://github.com/jpena-r7/cpython/commit/b54634b9cf6efb9db31d9dcfa310964f290c9451

2022-09-04 22:46 UTC, jpena-r7 commented on build.go
> +				return InstallPython(sourcePath, context, entry, dependency, cpythonLayer, logger)
Thanks for your help getting me going on this. I refactored the installer and created interfaces for the processes as well. I also added success and failure unit tests to validate everything works as expected. Let me know if those tests are sufficient.

See this commit:
https://github.com/jpena-r7/cpython/commit/c6a0f871dadf479a2ee378ef8dc12dd8637d1a6d

2022-09-04 22:47 UTC, jpena-r7 commented on integration/init_test.go
> +	defaultDependency postal.Dependency
This has been implemented in this commit:
https://github.com/jpena-r7/cpython/commit/b54634b9cf6efb9db31d9dcfa310964f290c9451

2022-09-04 22:51 UTC, jpena-r7 commented on integration/init_test.go
> +	Expect(cmd.Execute(pexec.Execution{
No worries. This has been implemented in this commit:
https://github.com/jpena-r7/cpython/commit/b54634b9cf6efb9db31d9dcfa310964f290c9451

The PR check (at the bottom of the page) is giving the following error which is related to this commit. I had to update the dependency version in order to make use of `pack.Builder.Inspect.Execute()`. I think you have to resolve it or let me know if I need to make any changes.

```
This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files
go.mod
go.sum
```

2022-09-04 22:52 UTC, jpena-r7 commented on integration/init_test.go
> +	builder       occam.Builder
Good call. This has been implemented as suggested in this commit:
https://github.com/jpena-r7/cpython/commit/b54634b9cf6efb9db31d9dcfa310964f290c9451

2022-09-04 23:06 UTC, jpena-r7 commented on detect_test.go
> +	context("when the BP_CPYTHON_CONFIGURE_FLAGS env var is set", func() {
Agreed and implemented in the following commit. Hopefully that is what you were looking for.

[Improve BP_CPYTHON_CONFIGURE_FLAGS tests](https://github.com/jpena-r7/cpython/commit/3d77eb4113fe17b0a8cde2632e7fedd22cda0950)

2022-09-04 23:07 UTC, jpena-r7 commented on detect_test.go
> +							ConfigureFlags: "-flag1 -flag2",
Good call, and thanks for the suggestion. Implemented in this commit:
[Improve BP_CPYTHON_CONFIGURE_FLAGS tests](https://github.com/jpena-r7/cpython/commit/3d77eb4113fe17b0a8cde2632e7fedd22cda0950)

2022-09-07 16:55 UTC, robdimsdale commented on build.go
> +				return InstallPython(sourcePath, context, entry, dependency, cpythonLayer, logger)
We discussed this offline, and I shared a proof-of-concept of what refactored tests might look like on [this fork](https://github.com/robdimsdale/cpython/tree/support-all-stacks).

2022-09-09 13:10 UTC, molssongroup commented
/easycla

2022-09-09 21:00 UTC, robdimsdale approved these changes
This looks great!

Thank you for your Herculean efforts on this PR! I'm really glad to see this feature added and I think the code is clear and maintainable.

There are probably some more refactors we can do, and I think there's a couple of missing unit tests, but I don't think they need to block the merging of this PR.

2022-09-12 14:13 UTC, jarias-lfx commented
/easycla

2022-09-12 17:59 UTC, robdimsdale commented
For anyone following along at home, I suggested that @jpena-r7 squash and rebase the commit, because the merge history was too complex for github to merge.

2022-09-12 18:00 UTC, robdimsdale commented
Auto-merge is enabled so once the CLA is sorted this will get merged!

2022-09-12 19:35 UTC, merged